### ISSUE TITLE
Receiving all events at once in Angular, not when they are sent by Jersey SSE

### ISSUE THREAD

**Issue by knowledgeplaces** [mpetazzoni/sse.js#19]
I generate SSE events with a Java app developed with Jersey 2.32 and running on Tomcat 9.
Once the get request is received, an event is generated every 500 milliseconds, and I have checked it works fine by outputting the event data on the Java console.
The client is an Angular 12 app. I have picked up your library as I need to add an authentification header to my request.
The client does receive the messages, but it receives them all at once, instead of receiving them as soon as they are sent by the server. 
I have attached files with my code. Any help really appreciated.
[angular-client-excerpt.txt](https://github.com/mpetazzoni/sse.js/files/6629890/angular-client-excerpt.txt)
[batch-process-monitoring.service.txt](https://github.com/mpetazzoni/sse.js/files/6629891/batch-process-monitoring.service.txt)
[server-side-events.service.txt](https://github.com/mpetazzoni/sse.js/files/6629892/server-side-events.service.txt)
[jersey-sse.txt](https://github.com/mpetazzoni/sse.js/files/6629893/jersey-sse.txt)

**Comment by knowledgeplaces** [comment]
The issue seems related to using sse.js with Angular.
I updated my code to run the request without authorization header and using the standard Angular http client GET requests, and events are received one by one.
Any update on my original code to make it work with sse.js appreciated.

**Comment by jayarjo** [comment]
Same here. Using Express on server and React on front-end. Does server needs to be implemented in.a special way for streaming to work?

**Comment by mpetazzoni** [comment]
First, you should isolate whether the issue is client-side, or server-side.

To check that the server is behaving correctly, manually issue an HTTP request (for example, with [`httpie`](https://httpie.org)):

```
$ http --verbose http://.../{batchId}
```

And check that you:

* Correctly get the `Content-Type: text/event-stream` header
* That the output is correctly streaming in chunks.

If that's fine, then the problem is client side, and you should check what headers are being sent, and what's being received. It would be ideal if you can get a trace of the HTTP interaction between your client and your server. `ngrep` can help here.

**Comment by mpetazzoni** [comment]
Given the same issue exists with EventSource, this seems like an issue with Angular's event / render loop.
