### ISSUE TITLE
SSE server recommendation

### ISSUE THREAD

**Issue by mrbluecoat** [mpetazzoni/sse.js#80]
Any recommendation for an open source SSE server that natively supports your additional withCredentials and POST two-way features?

Perhaps partnering with https://github.com/slact/nchan ?

**Comment by mpetazzoni** [comment]
@mrbluecoat It really depends on what you're trying to achieve. If it's just for simple testing, you can put something together relatively easily and quickly in Python (Flask or FastAPI w/ sse-starlette: https://medium.com/@Rachita_B/implementing-sse-server-side-events-using-fastapi-3b2d6768249e) or in Go (for example: https://github.com/mpetazzoni/sse-server). Otherwise, you can build on top of existing frameworks like Spring.
